### PR TITLE
Fixed urls for lua-language-server.json

### PR DESCRIPTION
**Pull request by astrochili**

### CODE REVIEW

**Comment by vlaaad** [comment]
The URL is incorrect, you have to use `release.zip` release artifact, not a source tree zip

**Comment by astrochili** [comment]
I've thought about this and it does sound logical. But who would update the release link every time? Now there is a link to an old release, for example.

It's like it needs a completely different solution, some kind of automatic parsing of the latest release version.

**Comment by astrochili** [comment]
At the moment almost all assets refer to the master for this reason.

**Comment by astrochili** [comment]
Oh, I'm sorry, now I get it. It's about what's a release and what's source. Now I understand

**Comment by astrochili** [comment]
Fixed! 👍

**Comment by vlaaad** [comment]
Thanks!

**Pull request merged**
